In [45]:
#### Libraries ###
import os
import glob
import pandas as pd
import numpy as np
import scanpy as sc

import scipy.sparse as sp  
from scipy.sparse import csr_matrix
from scipy.io import mmread


import matplotlib.pyplot as plt

os.chdir("/data/scottaa/cta_onco_fetal")

In [37]:
df_izar = pd.read_csv("datasets/ovarian_cancer_ccca/original_data/Data_Izar2020_Ovarian/Samples.csv")

df_nath = pd.read_csv("datasets/ovarian_cancer_ccca/original_data/Data_Nath2021_Ovarian/Samples.csv")

In [43]:
os.listdir("datasets/ovarian_cancer_ccca/original_data")

[file.split("_")[1] for file in os.listdir("datasets/ovarian_cancer_ccca/original_data")]

['Geistlinger2020',
 'Izar2020',
 'Nath2021',
 'Olalekan2021',
 'Olbrecht2021',
 'Qian2020',
 'Regner2021',
 'Shih2018',
 'Tang-Huau2018',
 'Zhang2019',
 'Zhang2022']

In [ ]:
    if subproject in ["Izar2020"]:
        matrix_path = os.path.join(original_data_dir, f"Data_{subproject}_Ovarian", "Exp_data_TPM.mtx")
    else:
        matrix_path = os.path.join(original_data_dir, f"Data_{subproject}_Ovarian", "Exp_data_UMIcounts.mtx")
    barcodes_path = os.path.join(original_data_dir, f"Data_{subproject}_Ovarian", "Cells.tsv")
    genes_path = os.path.join(original_data_dir, f"Data_{subproject}_Ovarian", "Genes.txt")
    

    X = mmread(matrix_path).tocsr().T

    genes = pd.read_csv(genes_path, header=None, sep="\t")
    barcodes = pd.read_csv(barcodes_path, header=None)

    adata = sc.AnnData(X)

    adata.var_names = genes[1].astype(str).values
    adata.obs_names = barcodes[0].astype(str).values

    print("var_names",adata.var_names[:10])
    print("obs_names", adata.obs_names[:10])

    adata.var_names_make_unique()

In [38]:


df_nath = df_nath.dropna(axis=1, how="all")

df_nath = df_nath.astype(str)

In [39]:
df_nath.to_csv("datasets/ovarian_cancer_ccca/original_data/Data_Nath2021_Ovarian/Samples copy.csv", index=False)

In [40]:
df_nath = pd.read_csv("datasets/ovarian_cancer_ccca/original_data/Data_Nath2021_Ovarian/Samples copy.csv")
df_nath

,sample,technology,n_cells,patient,cancer_type,sex,diagnosis_recurrence,disease_extent,sample_primary_met,site,...,chemotherapy_exposed,chemotherapy_response,targeted_rx_exposed,targeted_rx_response,ICB_exposed,ICB_response,ET_exposed,ET_response,post_sampling_rx_exposed,OS
0,P02,iCell8,97,P02,Ovarian Cancer,Female,NaN,metastatic,met,ascites,...,carbo/cisplatin +paclitaxel\nliposomal doxorub...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,carbo/cisplatin + gemcitabine\ntopotecan\npacl...,1049.0
1,P03,iCell8,51,P03,Ovarian Cancer,Female,NaN,metastatic,met,ascites,...,carbo/cisplatin +paclitaxel\n,NaN,NaN,NaN,NaN,NaN,NaN,NaN,paclitaxel\nfarletuzumab,929.0
2,P04,10x,5989,P04,Ovarian Cancer,Female,NaN,metastatic,met,ascites,...,carbo/cisplatin +paclitaxel\nliposomal doxorub...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,carbo/cisplatin\nanastrozole\npaclitaxel\nlipo...,2011.0
3,P05,10x,8161,P05,Ovarian Cancer,Female,diagnosis,metastatic,met,ascites,...,not exposed,not exposed,not exposed,not exposed,not exposed,not exposed,not exposed,not exposed,carbo/cisplatin +paclitaxel,448.0
4,P10,10x,159,P10,Ovarian Cancer,Female,diagnosis,metastatic,met,ascites/plerual effusion,...,not exposed,not exposed,not exposed,not exposed,not exposed,not exposed,not exposed,not exposed,NaN,NaN
5,P11,10x,1437,P11,Ovarian Cancer,Female,diagnosis,metastatic,met,ascites/plerual effusion,...,not exposed,not exposed,not exposed,not exposed,not exposed,not exposed,not exposed,not exposed,NaN,NaN
6,P12,10x,1612,P12,Ovarian Cancer,Female,diagnosis,metastatic,met,ascites/plerual effusion,...,not exposed,not exposed,not exposed,not exposed,not exposed,not exposed,not exposed,not exposed,NaN,NaN
7,P13,10x,2065,P13,Ovarian Cancer,Female,diagnosis,metastatic,met,ascites/plerual effusion,...,not exposed,not exposed,not exposed,not exposed,not exposed,not exposed,not exposed,not exposed,NaN,NaN
8,P14,10x,2799,P14,Ovarian Cancer,Female,diagnosis,metastatic,met,ascites/plerual effusion,...,not exposed,not exposed,not exposed,not exposed,not exposed,not exposed,not exposed,not exposed,NaN,NaN
9,P15,10x,1057,P15,Ovarian Cancer,Female,diagnosis,metastatic,met,ascites/plerual effusion,...,not exposed,not exposed,not exposed,not exposed,not exposed,not exposed,not exposed,not exposed,NaN,NaN
10,P16,10x,2291,P16,Ovarian Cancer,Female,diagnosis,metastatic,met,ascites/plerual effusion,...,not exposed,not exposed,not exposed,not exposed,not exposed,not exposed,not exposed,not exposed,NaN,NaN
11,P17,10x,2673,P17,Ovarian Cancer,Female,diagnosis,metastatic,met,ascites/plerual effusion,...,not exposed,not exposed,not exposed,not exposed,not exposed,not exposed,not exposed,not exposed,NaN,NaN
12,P18,10x,1215,P18,Ovarian Cancer,Female,NaN,metastatic,met,ascites/plerual effusion,...,"Carboplatin, Paclitaxel, Bevacizumab, carbopla...",NaN,not exposed,not exposed,not exposed,not exposed,tamoxifen,NaN,NaN,NaN
13,P19,10x,1404,P19,Ovarian Cancer,Female,NaN,metastatic,met,ascites/plerual effusion,...,"Carboplatin, Paclitaxel, Carboplatin, Paclitax...",NaN,niraparib,NaN,Pembrolizumab,NaN,not exposed,not exposed,NaN,NaN
14,P20,10x,1422,P20,Ovarian Cancer,Female,NaN,metastatic,met,ascites/plerual effusion,...,"Carboplatin, Paclitaxel, Carboplatin, Lipsomal...",NaN,niraparib,NaN,not exposed,not exposed,tamoxifen,NaN,NaN,NaN
15,P21,10x,5332,P21,Ovarian Cancer,Female,NaN,metastatic,met,ascites/plerual effusion,...,"Carboplatin, Paclitaxel, Doxil, Pemetrexed, Ca...",NaN,not exposed,not exposed,not exposed,not exposed,not exposed,not exposed,NaN,NaN
16,P23,10x,2142,P23,Ovarian Cancer,Female,NaN,metastatic,met,ascites/plerual effusion,...,"Carboplatin, Doxil, Carboplatin, Bevacuzimab, ...",NaN,niraparib,NaN,Pembrolizumab,NaN,letrozole,NaN,NaN,NaN
17,P24,10x,1823,P24,Ovarian Cancer,Female,NaN,metastatic,met,ascites/plerual effusion,...,"Cisplatin, Paclitaxel, Carboplatin, Docetaxel,...",NaN,rucaparib,NaN,Pembrolizumab,NaN,Anastrozole,NaN,NaN,NaN

In [69]:
original_data_dir = "datasets/ovarian_cancer_ccca/original_data"
subproject = "Geistlinger2020"
matrix_path = os.path.join(original_data_dir, f"Data_{subproject}_Ovarian", "Exp_data_UMIcounts.mtx")
barcodes_path = os.path.join(original_data_dir, f"Data_{subproject}_Ovarian", "Cells.csv")
genes_path = os.path.join(original_data_dir, f"Data_{subproject}_Ovarian", "Genes.txt")
sample_meta_path = os.path.join(original_data_dir, f"Data_{subproject}_Ovarian", "Samples.csv")

X = mmread(matrix_path).tocsr().T

genes = pd.read_csv(genes_path, header=None, sep=None, engine="python")
barcodes = pd.read_csv(barcodes_path, sep=None, engine="python")

adata = sc.AnnData(X)

adata.var_names = genes.iloc[:, -1].astype(str).values
adata.obs_names = barcodes["cell_name"].astype(str).values

adata.obs = barcodes.set_index("cell_name")

sample_meta_df = pd.read_csv(sample_meta_path)
sample_meta_df = sample_meta_df.dropna(axis=1, how="all")
sample_meta_df = sample_meta_df.astype(str)

# columns to add (exclude overlaps except 'sample')
cols_to_add = [c for c in sample_meta_df.columns if c not in adata.obs.columns or c == "sample"]

adata.obs = adata.obs.reset_index().merge(sample_meta_df[cols_to_add], on="sample", how="left").set_index("cell_name")
adata.obs = adata.obs.rename(columns={"sample": "sample_id"})

adata.obs

,sample_id,patient,cell_type,cell_subtype,complexity,umap1,umap2,g1s_score,g2m_score,cell_cycle_phase,...,hpca.celltype,encode.celltype,subtype,tumor_stage,tumor_grade,ct_response,cancer_type,technology,n_cells,histology
cell_name,,,,,,,,,,,,,,,,,,,,,
AAACCTGAGCTGCCCA-1_1,T59,T59,Macrophage,Macrophage,799,NaN,NaN,NaN,NaN,NaN,...,Macrophage,Macrophages,DIF,IV,3,resistant,Ovarian Cancer,10x,12659,HGSOC
AAACCTGAGTCATCCA-1_2,T59,T59,Macrophage,Macrophage,1022,-20.1389,3.4806,-0.0742,-0.1413,Not cycling,...,Macrophage,Macrophages,DIF,IV,3,resistant,Ovarian Cancer,10x,12659,HGSOC
AAACCTGCAAGCCCAC-1_3,T59,T59,Macrophage,Macrophage,1036,-18.0940,5.6027,0.0662,0.1092,Not cycling,...,Macrophage,Macrophages,IMR,IV,3,resistant,Ovarian Cancer,10x,12659,HGSOC
AAACCTGCAAGCGCTC-1_4,T59,T59,Malignant,Malignant,2571,15.1243,-24.7119,0.8839,0.2127,G1/S,...,Epithelial_cells,Epithelial cells,DIF,IV,3,resistant,Ovarian Cancer,10x,12659,HGSOC
AAACCTGCACGTAAGG-1_5,T59,T59,Malignant,Malignant,3402,11.8044,-24.9339,0.8818,1.0527,Intermediate,...,Epithelial_cells,Epithelial cells,DIF,IV,3,resistant,Ovarian Cancer,10x,12659,HGSOC
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TTTGTCACACAGCCCA-1_41027,T90,T90,T_cell,T_cell,908,NaN,NaN,NaN,NaN,NaN,...,T_cells,CD8+ T-cells,DIF,IVa,3,sensitive,Ovarian Cancer,10x,3630,HGSOC
TTTGTCACATTCTTAC-1_41028,T90,T90,Malignant,Malignant,3321,-6.1218,-34.1287,2.3058,0.8404,G1/S,...,iPS_cells,Epithelial cells,DIF,IVa,3,sensitive,Ovarian Cancer,10x,3630,HGSOC
TTTGTCAGTAGCTGCC-1_41029,T90,T90,Fibroblast,Fibroblast,2583,11.6674,5.2157,-0.2370,-0.0576,Not cycling,...,Fibroblasts,Fibroblasts,MES,IVa,3,sensitive,Ovarian Cancer,10x,3630,HGSOC
TTTGTCAGTTGAGGTG-1_41030,T90,T90,Fibroblast,Fibroblast,3401,12.8715,6.6801,0.1937,-0.0536,Not cycling,...,Tissue_stem_cells,Astrocytes,MES,IVa,3,sensitive,Ovarian Cancer,10x,3630,HGSOC
TTTGTCATCTGTGCAA-1_41031,T90,T90,T_cell,T_cell,962,NaN,NaN,NaN,NaN,NaN,...,T_cells,CD8+ T-cells,DIF,IVa,3,sensitive,Ovarian Cancer,10x,3630,HGSOC

In [68]:
adata.obs

,sample,patient,cell_type,cell_subtype,complexity,umap1,umap2,g1s_score,g2m_score,cell_cycle_phase,mp_top_score,mp_top,mp_assignment,hpca.celltype,encode.celltype,subtype,tumor_stage,tumor_grade,ct_response
cell_name,,,,,,,,,,,,,,,,,,,
AAACCTGAGCTGCCCA-1_1,T59,T59,Macrophage,Macrophage,799,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Macrophage,Macrophages,DIF,IV,3,resistant
AAACCTGAGTCATCCA-1_2,T59,T59,Macrophage,Macrophage,1022,-20.1389,3.4806,-0.0742,-0.1413,Not cycling,0.6188,MAC3,NaN,Macrophage,Macrophages,DIF,IV,3,resistant
AAACCTGCAAGCCCAC-1_3,T59,T59,Macrophage,Macrophage,1036,-18.0940,5.6027,0.0662,0.1092,Not cycling,0.4121,Lipid-associated,NaN,Macrophage,Macrophages,IMR,IV,3,resistant
AAACCTGCAAGCGCTC-1_4,T59,T59,Malignant,Malignant,2571,15.1243,-24.7119,0.8839,0.2127,G1/S,1.0352,Protein maturation,NaN,Epithelial_cells,Epithelial cells,DIF,IV,3,resistant
AAACCTGCACGTAAGG-1_5,T59,T59,Malignant,Malignant,3402,11.8044,-24.9339,0.8818,1.0527,Intermediate,1.6364,Cell Cycle - G2/M,Cell Cycle - G2/M,Epithelial_cells,Epithelial cells,DIF,IV,3,resistant
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TTTGTCACACAGCCCA-1_41027,T90,T90,T_cell,T_cell,908,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T_cells,CD8+ T-cells,DIF,IVa,3,sensitive
TTTGTCACATTCTTAC-1_41028,T90,T90,Malignant,Malignant,3321,-6.1218,-34.1287,2.3058,0.8404,G1/S,2.4331,Cell Cycle - G1/S,Cell Cycle - G1/S,iPS_cells,Epithelial cells,DIF,IVa,3,sensitive
TTTGTCAGTAGCTGCC-1_41029,T90,T90,Fibroblast,Fibroblast,2583,11.6674,5.2157,-0.2370,-0.0576,Not cycling,2.0755,Complement,Complement,Fibroblasts,Fibroblasts,MES,IVa,3,sensitive
TTTGTCAGTTGAGGTG-1_41030,T90,T90,Fibroblast,Fibroblast,3401,12.8715,6.6801,0.1937,-0.0536,Not cycling,0.6205,Myofibroblasts,NaN,Tissue_stem_cells,Astrocytes,MES,IVa,3,sensitive
TTTGTCATCTGTGCAA-1_41031,T90,T90,T_cell,T_cell,962,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T_cells,CD8+ T-cells,DIF,IVa,3,sensitive

In [64]:
adata.obs

,sample,patient,cell_type,cell_subtype,complexity,umap1,umap2,g1s_score,g2m_score,cell_cycle_phase,mp_top_score,mp_top,mp_assignment,hpca.celltype,encode.celltype,subtype,tumor_stage,tumor_grade,ct_response,sample_id
cell_name,,,,,,,,,,,,,,,,,,,,
AAACCTGAGCTGCCCA-1_1,T59,T59,Macrophage,Macrophage,799,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Macrophage,Macrophages,DIF,IV,3,resistant,T59
AAACCTGAGTCATCCA-1_2,T59,T59,Macrophage,Macrophage,1022,-20.1389,3.4806,-0.0742,-0.1413,Not cycling,0.6188,MAC3,NaN,Macrophage,Macrophages,DIF,IV,3,resistant,T59
AAACCTGCAAGCCCAC-1_3,T59,T59,Macrophage,Macrophage,1036,-18.0940,5.6027,0.0662,0.1092,Not cycling,0.4121,Lipid-associated,NaN,Macrophage,Macrophages,IMR,IV,3,resistant,T59
AAACCTGCAAGCGCTC-1_4,T59,T59,Malignant,Malignant,2571,15.1243,-24.7119,0.8839,0.2127,G1/S,1.0352,Protein maturation,NaN,Epithelial_cells,Epithelial cells,DIF,IV,3,resistant,T59
AAACCTGCACGTAAGG-1_5,T59,T59,Malignant,Malignant,3402,11.8044,-24.9339,0.8818,1.0527,Intermediate,1.6364,Cell Cycle - G2/M,Cell Cycle - G2/M,Epithelial_cells,Epithelial cells,DIF,IV,3,resistant,T59
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TTTGTCACACAGCCCA-1_41027,T90,T90,T_cell,T_cell,908,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T_cells,CD8+ T-cells,DIF,IVa,3,sensitive,T90
TTTGTCACATTCTTAC-1_41028,T90,T90,Malignant,Malignant,3321,-6.1218,-34.1287,2.3058,0.8404,G1/S,2.4331,Cell Cycle - G1/S,Cell Cycle - G1/S,iPS_cells,Epithelial cells,DIF,IVa,3,sensitive,T90
TTTGTCAGTAGCTGCC-1_41029,T90,T90,Fibroblast,Fibroblast,2583,11.6674,5.2157,-0.2370,-0.0576,Not cycling,2.0755,Complement,Complement,Fibroblasts,Fibroblasts,MES,IVa,3,sensitive,T90
TTTGTCAGTTGAGGTG-1_41030,T90,T90,Fibroblast,Fibroblast,3401,12.8715,6.6801,0.1937,-0.0536,Not cycling,0.6205,Myofibroblasts,NaN,Tissue_stem_cells,Astrocytes,MES,IVa,3,sensitive,T90
TTTGTCATCTGTGCAA-1_41031,T90,T90,T_cell,T_cell,962,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T_cells,CD8+ T-cells,DIF,IVa,3,sensitive,T90